// Copyright (c) 2020 DistAlchemist
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package locator

import "github.com/DistAlchemist/Mongongo/network"

// RackAwareStrategy implements RackStrategy interface
type RackAwareStrategy struct {
	//
}

// GetStorageEndPoints return tokens generated by consistent hashing
// input is a list of rowKeys
func (ras RackAwareStrategy) GetStorageEndPoints(token uint64) map[network.EndPoint]network.EndPoint {
	return map[network.EndPoint]network.EndPoint{
		{HostName: "localhost", Port: "11111"}: {HostName: "localhost", Port: "11111"}}
}
