// Copyright (c) 2020 DistAlchemist
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

package gms

import "sync/atomic"

// Version is a unique version number for
// any state that is generated by the
// local node
var Version int32 = 0

// GetNextVersion get the next version
func GetNextVersion() int32 {
	atomic.AddInt32(&Version, 1)
	return Version
}
